$('#quiz').quiz({
  //resultsScreen: '#results-screen',
  //counter: false,
  //homeButton: '#custom-home',
  counterFormat: 'Question %current of %total',
  questions: [
    {
      'q':'A unit of power (equivalent to one Joule per second) used to express laser power.',
   'options': ['Watts','Joules','Hertz','Current','Ohms'],
   'correctIndex':0,
   'correctResponse':'Correct!',
   'incorrectResponse':'Your response was incorrect.'
}, {
   'q':'The distance between diametrically opposed points in the cross section of a circular beam.',
   'options': ['Event Diameter','Beam Attenuator','Event Horizon','Beam Diameter','Beam Radius'],
   'correctIndex':3,
   'correctResponse':'Correct!',
   'incorrectResponse':'Your response was incorrect.'
}, {
   'q':'A disturbance which propagates outward from an electric charge that oscillates or is accelerated. Includes radio waves; X-rays; gamma rays; and infrared, ultraviolet, and visible light.',
   'options': ['Electromagnetic Wave','Acoustic Wave','Shock Wave','Tidal Wave','Noise Wave'],
   'correctIndex':0,
   'correctResponse':'Correct!',
   'incorrectResponse':'Your response was incorrect.'
}, {
   'q':'The highest power or energy density (in W/cm2 or J/cm2) of a light source that has a negligible risk for causing damage to an exposed surface of the body. It is measured at the cornea or skin for a given wavelength and exposure time.',
   'options': ['FDA Standards','Maximum Permissible Exposure','OSHA Requirements','Noise Limit','Power Max'],
   'correctIndex':1,
   'correctResponse':'Correct!',
   'incorrectResponse':'Your response was incorrect.'
}, {
   'q':'The input level at which lasing begins during excitation of the laser medium.',
   'options': ['Median','Threshold','Gain','Ceiling','Gate'],
   'correctIndex':1,
   'correctResponse':'Correct!',
   'incorrectResponse':'Your response was incorrect.'
}, {
   'q':'To transform radiant energy into a different form, with a resultant rise in temperature.',
   'options': ['Dissolve','Absorb','Repel','Dilute','Reflect'],
   'correctIndex':1,
   'correctResponse':'Correct!',
   'incorrectResponse':'Your response was incorrect.'
}, {
   'q':'The product of power (watts) and duration (seconds). One watt second = one Joule.',
   'options': ['Frequency','Energy','Amplitude','Resistance','Capacitance'],
   'correctIndex':1,
   'correctResponse':'Correct!',
   'incorrectResponse':'Your response was incorrect.'
}, {
   'q':'Negatively charged particle of an atom.',
   'options': ['Quark','Proton','Nucleus','Electron','Photon'],
   'correctIndex':3,
   'correctResponse':'Correct!',
   'incorrectResponse':'Your response was incorrect.'
}, {
   'q':'The mirror in a laser which combines two or more wavelengths into a coaxial beam.',
   'options': ['Beam Splitter','Beam Bounce','Collimator','Combiner Mirror','Divergence'],
   'correctIndex':3,
   'correctResponse':'Correct!',
   'incorrectResponse':'Your response was incorrect.'
}, {
   'q':'An interlock where the failure of a single mechanical or electrical component of the interlock will cause the system to go into, or remain in, a safe mode.',
   'options': ['First Aid Kit','Fire Exstinguisher','Failsafe Interlock','Fail Lock','Inter Fail'],
   'correctIndex':2,
   'correctResponse':'Correct!',
   'incorrectResponse':'Your response was incorrect.'
}, {
   'q':'A solid with a regular array of atoms. Sapphire (Ruby Laser) and YAG (Nd:YAG laser) are two crystalline materials used as laser sources.',
   'options': ['Rock','Facet','Cube','Crystal','Lens'],
   'correctIndex':3,
   'correctResponse':'Correct!',
   'incorrectResponse':'Your response was incorrect.'
}, {
   'q':'An instrument which measures the energy, usually as heat generated by absorption of the laser beam.',
   'options': ['Multimeter','Lightmeter','Calorimeter','Fluxmeter','Micrometer'],
   'correctIndex':2,
   'correctResponse':'Correct!',
   'incorrectResponse':'Your response was incorrect.'
}, {
   'q':'The range of electromagnetic radiation frequencies detected by the eye, or the wavelength range from about 400 to 760 nanometers. The term is sometimes used loosely to include radiation beyond visible limits.',
   'options': ['Radio','Sound','Light','Microwave','X-Ray'],
   'correctIndex':2,
   'correctResponse':'Correct!',
   'incorrectResponse':'Your response was incorrect.'
}, {
   'q':'The maximum flow of electric current in a conductor; in a laser, the point at which further electrical input will not increase laser output.',
   'options': ['Homeostasis','Current Saturation','Equalibrium','Point Break','Event Horizon'],
   'correctIndex':1,
   'correctResponse':'Correct!',
   'incorrectResponse':'Your response was incorrect.'
}, {
   'q':'Takes place when different parts of a beam incident on a surface are reflected over a wide range of angles in accordance with Lamberts Law. The intensity will fall-off as the inverse of the square of the distance away from the surface and also obey a Cosine Law of reflection.',
   'options': ['Diffuse Reflection','Shutter Speed','Amplification','Resistance','Light'],
   'correctIndex':0,
   'correctResponse':'Correct!',
   'incorrectResponse':'Your response was incorrect.'
}, {
   'q':'The length of the light wave, usually measured from crest to crest, which determines its color. Common units of measurement are the micrometer (micron), the nanometer, and (earlier) the Angstrom unit.',
   'options': ['Crest','Frequency','Wavelength','Function','Phase'],
   'correctIndex':2,
   'correctResponse':'Correct!',
   'incorrectResponse':'Your response was incorrect.'
}, {
   'q':'The return of radiant energy (incident light) by a surface, with no change in wavelength.',
   'options': ['Refraction','Deflection','Reflection','Diffusion','Diffraction'],
   'correctIndex':2,
   'correctResponse':'Correct!',
   'incorrectResponse':'Your response was incorrect.'
}, {
   'q':'The change of direction of propagation of any wave, such as an electromagnetic wave, when it passes from one medium to another in which the wave velocity is different. The bending of incident rays as they pass from one medium to another (eg.: air to glass).',
   'options': ['Reflection','Deflection','Diffusion','Refraction','Diffraction'],
   'correctIndex':3,
   'correctResponse':'Correct!',
   'incorrectResponse':'Your response was incorrect.'
}, {
   'q':'The number of pulses produced per second by a laser.',
   'options': ['Resistance','Amplitude','Focus','Pulse Repetition Frequency','Resonance'],
   'correctIndex':3,
   'correctResponse':'Correct!',
   'incorrectResponse':'Your response was incorrect.'
}, {
   'q':'The number of light waves passing a fixed point in a given unit of time, or the number of complete vibrations in that period.',
   'options': ['Frequency','Active Medium','Amplitude','Wavelength','Repition'],
   'correctIndex':0,
   'correctResponse':'Correct!',
   'incorrectResponse':'Your response was incorrect.'
}, {
   'q':'The rate of energy delivery expressed in watts (joules per second). Thus: 1 Watt = 1 Joule x 1 Sec.',
   'options': ['Capacitance','Voltage','Power','Current','Resistance'],
   'correctIndex':2,
   'correctResponse':'Correct!',
   'incorrectResponse':'Your response was incorrect.'
}, {
   'q':'In quantum theory, the elemental unit of light, having both wave and particle behavior. It has motion, but no mass or charge.', 
   'options': ['Electron','Photon','Proton','Nucleus','Quark'],
   'correctIndex':1,
   'correctResponse':'Correct!',
   'incorrectResponse':'Your response was incorrect.'
}, {
   'q':'Waves are in phase with each other when all the troughs and peaks coincide and are locked together. The result is a reinforced wave in increased amplitude (brightness).',
   'options': ['Loaded','Mode','Locked','Sync','Phase'],
   'correctIndex':4,
   'correctResponse':'Correct!',
   'incorrectResponse':'Your response was incorrect.'
}, {
   'q':'The attribute of a surface not allowing light to pass.',
   'options': ['Fluidness','Transparency','Translucence','Opacity','Solidity'],
   'correctIndex':3,
   'correctResponse':'Correct!',
   'incorrectResponse':'Your response was incorrect.'
}, {
   'q':'Theoretically, light consisting of just one wavelength.',
   'options': ['Solochromonic Light','Monoharmonic Light','Harmonic Light','Chromatic Light','Monochromatic Light'],
   'correctIndex':4,
   'correctResponse':'Correct!',
   'incorrectResponse':'Your response was incorrect.'
}, {
   'q':'Unwanted minor currents or voltages in an electrical system.',
   'options': ['Voltage','Silence','Bugs','Noise','Gremlins'],
   'correctIndex':3,
   'correctResponse':'Correct!',
   'incorrectResponse':'Your response was incorrect.'
}, {
   'q':'A photographic film or plate containing interference patterns created by the coherence of laser light. A three dimensional image may be reconstructed from a hologram. Here are transmission, reflection or integral holograms.',
   'options': ['Hologram','Photograph','Lasergraph','Lithograph','Telegraph'],
   'correctIndex':0,
   'correctResponse':'Correct!',
   'incorrectResponse':'Your response was incorrect.'
}, {
   'q':'An opening through which radiation can pass.',
   'options': ['Aperture','Door','Window','Iris','Shutter'],
   'correctIndex':0,
   'correctResponse':'Correct!',
   'incorrectResponse':'Your response was incorrect.'
}, {
   'q':'Positively charged particle of an atom.',
   'options': ['Protein','Quark','Photons','Electron','Proton'],
   'correctIndex':4,
   'correctResponse':'Correct!',
   'incorrectResponse':'Your response was incorrect.'
}, {
   'q':'A digital chip (computer) that operates, controls and monitors some lasers.',
   'options': ['Fuse','LED','Micro-processor','PCB','Diode'],
   'correctIndex':2,
   'correctResponse':'Correct!',
   'incorrectResponse':'Your response was incorrect.'
}, {
   'q':'The maximum value of the electro-magnetic wave, measured from the mean to the extreme; simply stated: the height of the wave.',
   'options': ['Median','Top','Crest','Frequency','Amplitude'],
   'correctIndex':4,
   'correctResponse':'Correct!',
   'incorrectResponse':'Your response was incorrect.'
}, {
   'q':'The negatively charged electrical element by which electrons enter an electrical device.',
   'options': ['Xenon','Cathode','Diode','Capacitor','Coherence'],
   'correctIndex':1,
   'correctResponse':'Correct!',
   'incorrectResponse':'Your response was incorrect.'
}, {
   'q':'A shaped piece of optically transparent material which depending on its shape is used to either converge or diverge light.',
   'options': ['Thimble','Glass','Cornea','Iris','Lens'],
   'correctIndex':4,
   'correctResponse':'Correct!',
   'incorrectResponse':'Your response was incorrect.'
}, {
   'q':'Collection of atoms or molecules capable of undergoing stimulated emission at a given wavelength.',
   'options': ['Brightness','Diffraction','Reflection','Active Medium','Combiner Mirror'],
   'correctIndex':3,
   'correctResponse':'Correct!',
   'incorrectResponse':'Your response was incorrect.'
}, {
   'q':'The increase in the diameter of the laser beam with distance from the exit aperture.',
   'options': ['Collimation','Convergence','Divergence','Focus','Amplification'],
   'correctIndex':2,
   'correctResponse':'Correct!',
   'incorrectResponse':'Your response was incorrect.'
}, {
   'q':'The department of the Food and Drug Association that deals with laser safety',
   'options': ['NASA','NIST','CDRH','ATF','FDA'],
   'correctIndex':2,
   'correctResponse':'Correct!',
   'incorrectResponse':'Your response was incorrect.'
}, {
   'q':'A term describing light as waves which are in phase in both time and space.',
   'options': ['Coherence','Synergy','Sync','Tolerable','Visible'],
   'correctIndex':0,
   'correctResponse':'Correct!',
   'incorrectResponse':'Your response was incorrect.'
}, {
   'q':'The growth of the radiation field in the laser resonator cavity. As the light wave bounces back and forth between the cavity mirrors, it is amplified by stimulated emission on each pass through the active medium.',
   'options': ['Amplification','Beam Collimation','Aperture','Stimulation','Multiplication'],
   'correctIndex':0,
   'correctResponse':'Correct!',
   'incorrectResponse':'Your response was incorrect.'
}, {
   'q':'An optical device that increases beam diameter while decreasing beam divergence (spread). In its simplest form consists of two lenses, the first to diverge the beam and the second to re-collimate it. Also called an upcollimator.',
   'options': ['Reflector','Beam Expander','Beam Divergence','Phase','Magnetic Field'],
   'correctIndex':1,
   'correctResponse':'Correct!',
   'incorrectResponse':'Your response was incorrect.'
}, {
   'q':'An electrical element in laser excitation which attracts electrons from a cathode.',
   'options': ['Anode','Photon','Capacitor','Resistor','Diode'],
   'correctIndex':0,
   'correctResponse':'Correct!',
   'incorrectResponse':'Your response was incorrect.'
}, {
   'q':'An optical device using controlled reflection to produce two beams from a single incident beam.',
   'options': ['Beam Splitter','Beam Collimater','Beam Expander','Beam Seperator','Beam Finder'],
   'correctIndex':0,
   'correctResponse':'Correct!',
   'incorrectResponse':'Your response was incorrect.'
}, {
   'q':'Angle of beam spread which is measured in radians.',
   'options': ['Convex','Beam Divergence','Coherence','Acute','Obtuse'],
   'correctIndex':1,
   'correctResponse':'Correct!',
   'incorrectResponse':'Your response was incorrect.'
}, {
   'q':'What does the acronym LASER stand for?',
   'options': ['Light Anonodized with Synthesised Electric Ramping','Light Altered by Stimulated Emission of Radiation','Light Amplification by Stimulated Electrons of Radiation','Light Action by Stimulated Emission of Radar','Light Amplification by Stimulated Emission of Radiation'],
   'correctIndex':4,
   'correctResponse':'Correct!',
   'incorrectResponse':'Your response was incorrect.'
}, {
   'q':'The visual sensation of the luminous intensity of a light source.',
   'options': ['Distortion','Warmth','Contrast','Brightness','Blurriness'],
   'correctIndex':3,
   'correctResponse':'Correct!',
   'incorrectResponse':'Your response was incorrect.'
    }
  ]
});